#ifndef INCLUDED_LBAMTRUCKDRAWSTRATEGY_H_
#define INCLUDED_LBAMTRUCKDRAWSTRATEGY_H_

interface iLBAMTruckDrawStrategy
{
   virtual void SetColor(COLORREF color) = 0;
};

#endif // INCLUDED_LBAMTRUCKDRAWSTRATEGY_H_