<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets">
  </ImportGroup>
  <PropertyGroup Label="UserMacros" />
  <PropertyGroup>
    <SourcePath>$(SourcePath)</SourcePath>
    <ExecutablePath>$(XSDDIR)\bin;$(ExecutablePath)</ExecutablePath>
    <IncludePath>$(XSDDIR)\include;$(IncludePath)</IncludePath>
  </PropertyGroup>
  <ItemDefinitionGroup>
    <CXX_Tree_Mapping_Rule />
    <CXX_Tree_Mapping_Rule>
      <CxxStd>0</CxxStd>
      <CharType>1</CharType>
    </CXX_Tree_Mapping_Rule>
    <ClCompile>
      <PreprocessorDefinitions>LIBXERCES_C_SHARED;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <AdditionalIncludeDirectories>$(ARPDIR)\WBFL\Apache\XALANCPKG-112-324-X64-VC143\include;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    </ClCompile>
  </ItemDefinitionGroup>
  <ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <Link>
      <AdditionalDependencies>$(XSDDIR)\lib\xerces-c.dll.lib;$(ARPDIR)\WBFL\Apache\XALANCPKG-112-324-X64-VC143\lib\Xalan-C_1.lib;%(AdditionalDependencies)</AdditionalDependencies>
    </Link>
  </ItemDefinitionGroup>
  <ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <Link>
      <AdditionalDependencies>$(XSDDIR)\lib\xerces-cd.dll.lib;$(ARPDIR)\WBFL\Apache\XALANCPKG-112-324-X64-VC143\lib\Xalan-C_1D.lib;%(AdditionalDependencies)</AdditionalDependencies>
    </Link>
  </ItemDefinitionGroup>
  <ItemGroup />
</Project>