//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by GenericBridge.rc
//
#define IDS_PROJNAME                    100
#define IDR_GENERICBRIDGE               101
#define IDR_STAGE                       102
#define IDR_STAGECOLLECTION             103
#define IDR_BRIDGEPIER                  105
#define IDR_PIER                        106
#define IDR_PIERCOLLECTION              107
#define IDR_COLUMNSEGMENT               109
#define IDR_GIRDERSPACING               110
#define IDR_ADAPTSTATION                111
#define IDR_SUPERSTRUCTUREMEMBER        112
#define IDR_SEGMENT                     113
#define IDR_CROSSSECTION                114
#define IDR_SEGMENTCROSSSECTION         115
#define IDR_SEGMENTITEM                 116
#define IDR_FILTEREDSEGMENTCOLLECTION   117
#define IDR_STRESSPOINT                 119
#define IDR_STRESSPOINTCOLLECTION       120
#define IDR_DISTRIBUTIONFACTOR          121
#define IDR_POINTOFINTEREST             122
#define IDR_POINTOFINTERESTCOLLECTION   123
#define IDR_COLUMN                      125
#define IDR_COLUMNCOLLECTION            126
#define IDR_COLUMNLAYOUT                127
#define IDR_LINEARCROSSBEAM             128
#define IDR_TRANSVERSEPIERDESCRIPTION   129
#define IDR_POINTLOAD                   130
#define IDR_FSHAPEBARRIER               131
#define IDR_LINEARTENDONSEGMENT         133
#define IDR_TENDON                      134
#define IDR_TENDONCOLLECTION            135
#define IDR_PRESTRESSINGSTRAND          136
#define IDR_BULBTEE                     137
#define IDR_EDGEPATHSTRATEGY            138
#define IDR_MULTIWEBSECTION             139
#define IDR_VOIDEDSLABSECTION           140
#define IDR_VOIDEDSLABSECTION2          141
#define IDR_BOXBEAMSECTION              142
#define IDR_MULTIWEBSECTION2            143
#define IDR_SIDEWALKBARRIER             144
#define IDR_FLANGEDGIRDERENDBLOCKSEGMENT 145
#define IDR_TAPEREDGIRDERSEGMENT        146
#define IDR_VOIDEDSLABENDBLOCKSEGMENT   147
#define IDR_THICKENEDFLANGEBULBTEESEGMENT 148
#define IDR_DECKEDSLABBEAMSECTION       149
#define IDR_DECKEDSLABBEAMENDBLOCKSEGMENT 150
#define IDR_BOXBEAMENDBLOCKSEGMENT      151
#define IDR_UGIRDERSECTION2ENDBLOCKSEGMENT 152
#define IDR_FLANGEDSPLICEDGIRDERSEGMENT 153
#define IDR_USPLICEDGIRDERSEGMENT       154
#define IDR_NUSPLICEDGIRDERSEGMENT      155
#define IDR_PARABOLICTENDONSEGMENT      156
#define IDR_OFFSETTENDON                157
#define IDR_PRISMATICSUPERSTRUCTUREMEMBERSEGMENT 158
#define IDR_GENERICBARRIER              163
#define IDR_REBAR                       164
#define IDR_REBARSECTIONITEM            165
#define IDR_REBARSECTION                166
#define IDR_REBARROWPATTERN             167
#define IDR_CROSSBEAMREBARPATTERN       168
#define IDR_FLEXREBARLAYOUTITEM         169
#define IDR_REBARLAYOUT                 170
#define IDR_REBARFACTORY                171
#define IDR_BRIDGEDECKREBARLAYOUTITEM   172
#define IDR_NMBRIDGEDECKREBARLAYOUTITEM 173
#define IDR_BRIDGEDECKREBARPATTERN      174
#define IDR_FIXEDLENGTHREBARLAYOUTITEM  175
#define IDR_BEARINGLAYOUT               176
#define IDR_REBARROWFACEPATTERN         177
#define IDR_CASTING_REGION              178
#define IDR_CASTING_REGIONS             179
#define IDR_NUDECKEDBULBTEESECTION      180
#define IDR_PCIDECKEDBULBTEESECTION     181
#define IDS_STAGENAME                   201
#define IDS_STAGEDESCRIPTION            203
#define IDC_SPANS                       204
#define IDC_PIERS                       205
#define IDD_ADDSTAGE                    207
#define IDC_GRID                        207
#define IDC_ADD                         208
#define IDD_SPANINFO                    209
#define IDC_TRANSLATE                   209
#define IDC_MOVE                        210
#define IDD_PIERLAYOUT                  211
#define IDC_TRANSLATE_AMOUNT            212
#define IDC_TRANSLATE_AMOUNT_UNIT       213
#define IDD_SPANLAYOUT                  214
#define IDD_GIRDERLINES                 214
#define IDD_MOVEBRIDGE                  215
#define IDC_PIER                        216
#define IDC_STATION                     217
#define IDC_BRIDGEOFFSET                218
#define IDC_BYSPANLENGTH                218
#define IDC_BRIDGEOFFSET_UNIT           219
#define IDD_SPANLENGTH                  220
#define IDR_BRIDGE_MENU                 221
#define IDC_PIER_LABEL                  222
#define IDD_LONG_PIER                   223
#define IDC_ORIENTATION                 224
#define IDC_SUPPORT_TYPE                225
#define IDC_CONNECTIVITY                226
#define IDC_CONTINUITY_STAGE            227
#define IDC_HEIGHT                      228
#define IDC_OFFSET                      229
#define IDC_HEIGHT_UNIT                 230
#define IDC_OFFSET_UNIT                 231
#define IDC_HEIGHT_LABEL                232
#define IDC_OFFSET_LABEL                233
#define IDC_STAGE_LABEL                 234
#define IDC_INSERT                      235
#define IDC_REMOVE                      236
#define IDC_MOVE_UP                     237
#define IDC_MOVE_DOWN                   238
#define IDB_ROLLER                      239
#define IDC_FRACTIONAL                  239
#define IDB_PINNED                      240
#define IDC_GEOMETRY_FRAME              240
#define IDB_INTEGRAL                    241
#define IDC_LINKED_PIER                 241
#define IDB_HINGED                      242
#define IDC_EDIT_MASTER                 242
#define IDB_HINGED_INTEGRAL             243
#define IDC_SPAN_LENGTH                 246
#define IDC_SPAN_LENGTH_UNIT            247
#define IDC_OPTION                      248
#define IDC_SPANLENGTH_OPTION           248
#define IDC_RADIO2                      249
#define IDC_STATION_OPTION              249
#define IDC_COPY                        251
#define IDC_PASTE                       252
#define IDC_NUM_GIRDERLINES             253
#define IDC_UNIFORM_GIRDER_SPACING      254
#define IDC_NONUNIFORM_GIRDER_SPACING   255
#define IDC_GIRDER_SPACING              256
#define IDC_EDIT_GIRDER_SPACING         257
#define IDC_STRAIGHT                    258
#define IDC_CURVED                      259
#define IDC_GIRDER_SPACING_UNIT         260
#define IDD_INSERTPIER                  261
#define IDD_GIRDERSPACING1              263
#define IDC_LABEL                       263
#define IDD_GIRDERSPACING               264
#define IDD_MEASURE                     265
#define IDC_MEASURE                     265
#define IDC_SPIN                        266
#define IDD_SUPERSTRUCTUREMEMBERS       266
#define IDC_LINKSOURCE                  267
#define IDC_SUPPORT_CONDITION           268
#define IDD_TRANSV_PIER                 268
#define IDC_CONNECTIVITY_LABEL          269
#define IDC_SEGMENTS                    269
#define IDD_SEGMENTS                    269
#define IDC_GRID_INFO                   270
#define IDC_SORT                        271
#define IDD_STRESSPOINTS                271
#define IDR_TEMPORARYPIERITEM           272
#define IDR_TEMPORARYPIERITEMCOLLECTION 273
#define IDR_MATERIAL                    275
#define IDR_CASTSLAB                    276
#define IDR_ALIGNMENTOFFSETSTRATEGY     277
#define IDR_PRECASTSLAB                 278
#define IDR_OVERLAYSLAB                 279
#define IDR_FLANGEDBEAM                 280
#define IDR_FLANGEDBEAM2                281
#define IDR_NUGIRDERSECTION             282
#define IDC_SYMMETRICAL                 283
#define IDR_UGIRDERSECTION              284
#define IDR_UGIRDERSECTION2             285
#define IDR_SUPERSTRUCTUREMEMBERCOLLECTION 286
#define IDC_TITLE                       287
#define IDC_LINKAGE                     288
#define IDC_START_OFFSET                293
#define IDC_END_OFFSET                  294
#define IDC_END_OFFSET_UNIT             295
#define IDC_START_OFFSET_UNIT           296
#define IDC_TOTAL_LENGTH                297
#define IDC_STAGE_TAB                   305
#define IDC_START_OFFSET_LABEL          313
#define IDC_END_OFFSET_LABEL            314
#define IDS_E_NUMGIRDERLINES            512
#define IDS_E_PIERINDEX                 513
#define IDS_E_SPANINDEX                 514
#define IDS_E_SPACEINDEX                515
#define IDS_E_GIRDERSPACING             516
#define IDS_E_SPACING                   516
#define IDS_E_AREA                      517
#define IDS_E_MOMENTOFINERTIA           518
#define IDS_E_MODULUSOFELASTICITY       519
#define IDS_E_DENSITY                   520
#define IDS_E_WIDTH                     521
#define IDS_E_THERMALCOEFF              522
#define IDS_E_LENGTH                    523
#define IDS_E_CANTLINKSOURCE            524
#define IDS_E_CANTLINKTOSELF            525
#define IDS_E_CANTEDITLINKTARGET        526
#define IDS_E_NO_SEGMENTS_FOR_STAGE     527
#define IDS_E_LOCATION_OUT_OF_RANGE     528
#define IDS_E_LESS_THAN_MIN_GIRDER_LINES 529
#define IDS_E_STAGE_NOT_FOUND           530
#define IDS_E_LOCATION                  531
#define IDS_E_INVALID_NAME              532
#define IDS_E_DUPLICATENAME             533
#define IDS_E_FRACTIONAL_EXPECTED       534
#define IDS_E_ABSOLUTE_EXPECTED         535
#define IDS_E_ID_IN_USE                 536
#define IDS_E_OVERHANG                  537
#define IDS_E_LESS_THAN_MIN_COLUMNS     538
#define ID_EDIT_FRAMINGPLAN             32773
#define ID_EDIT_MOVEBRIDGE              32774
#define ID_EDIT_SPANLENGTHS             32775
#define ID_EDIT_ALIGNMENT               32778

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        285
#define _APS_NEXT_COMMAND_VALUE         32780
#define _APS_NEXT_CONTROL_VALUE         319
#define _APS_NEXT_SYMED_VALUE           180
#endif
#endif
