///////////////////////////////////////////////////////////////////////
// CORE - Core elements of the Agent-Broker Architecture
// Copyright © 1999-2023  Washington State Department of Transportation
//                        Bridge and Structures Office
//
// This library is a part of the Washington Bridge Foundation Libraries
// and was developed as part of the Alternate Route Project
//
// This library is free software; you can redistribute it and/or modify it under
// the terms of the Alternate Route Library Open Source License as published by 
// the Washington State Department of Transportation, Bridge and Structures Office.
//
// This program is distributed in the hope that it will be useful, but is distributed 
// AS IS, WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
// or FITNESS FOR A PARTICULAR PURPOSE. See the Alternate Route Library Open Source 
// License for more details.
//
// You should have received a copy of the Alternate Route Library Open Source License 
// along with this program; if not, write to the Washington State Department of 
// Transportation, Bridge and Structures Office, P.O. Box  47340, 
// Olympia, WA 98503, USA or e-mail Bridge_Support@wsdot.wa.gov
///////////////////////////////////////////////////////////////////////

// Core.idl : IDL source for Core.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (Core.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
import "WBFLTypes.idl";
import "WBFLTools.idl";

cpp_quote("/////////////////////////////////////////////////////////////////////////////")
cpp_quote("// IBroker, IBrokerInit, IBrokerPersist status codes")
cpp_quote("#define BROKER_E_FIRST    MAKE_SCODE(SEVERITY_ERROR,   FACILITY_ITF, 0x0200)")
cpp_quote("#define BROKER_E_LAST     MAKE_SCODE(SEVERITY_ERROR,   FACILITY_ITF, 0x020F)")
cpp_quote("")
cpp_quote("#define BROKER_E_LOADAGENT           (BROKER_E_FIRST+0)")
cpp_quote("// Error loading or initalizing an agent")
cpp_quote("#define BROKER_E_ADDAGENT            (BROKER_E_FIRST+1)")
cpp_quote("#define BROKER_E_INITAGENT           (BROKER_E_FIRST+2)")
cpp_quote("// Error loading adding an agent")

cpp_quote("/////////////////////////////////////////////////////////////////////////////")
cpp_quote("// IAgent, IAgentPersist, IAgentPersist2 status codes")
cpp_quote("#define AGENT_E_FIRST    MAKE_SCODE(SEVERITY_ERROR,   FACILITY_ITF, 0x0200)")
cpp_quote("#define AGENT_E_LAST     MAKE_SCODE(SEVERITY_ERROR,   FACILITY_ITF, 0x020F)")
cpp_quote("#define AGENT_S_FIRST    MAKE_SCODE(SEVERITY_SUCCESS, FACILITY_ITF, 0x0200)")
cpp_quote("#define AGENT_S_LAST     MAKE_SCODE(SEVERITY_SUCCESS, FACILITY_ITF, 0x020F)")

cpp_quote("// Agent wants a second pass during initialization")
cpp_quote("#define AGENT_S_SECONDPASSINIT	(AGENT_S_FIRST+0)")

cpp_quote("// Agent must implement the IAgentEx interface")
cpp_quote("#define AGENT_E_NOTAGENTEX    	(AGENT_E_FIRST+0)")

cpp_quote("/////////////////////////////////////////////////////////////////////////////")
cpp_quote("// IProgress status codes")
cpp_quote("#define PROGRESS_E_FIRST    MAKE_SCODE(SEVERITY_ERROR,   FACILITY_ITF, 0x0200)")
cpp_quote("#define PROGRESS_E_LAST     MAKE_SCODE(SEVERITY_ERROR,   FACILITY_ITF, 0x020F)")
cpp_quote("")
cpp_quote("#define PROGRESS_E_CREATE           (PROGRESS_E_FIRST+0)")
cpp_quote("// Error creating progress window")

cpp_quote("// Progress Window Flags")
cpp_quote("#define PW_ALL        0x0000")
cpp_quote("#define PW_NOMESSAGE  0x0001")
cpp_quote("#define PW_NOGAUGE    0x0002")
cpp_quote("#define PW_NOCANCEL   0x0004")



[
	uuid(D820A190-2BE4-11D2-8EB3-006097DF3C68),
	version(1.1),
	helpstring("WBFLCore Library")
]
library WBFLCore
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

   interface IBroker;


   [
	
		uuid(FF34DB70-2BEF-11d2-8EB3-006097DF3C68),
	
		helpstring("IProgress Interface"),
		pointer_default(unique)
	]
	interface IProgress : IUnknown
	{
		[helpstring("method CreateProgressWindow")] HRESULT CreateProgressWindow([in] DWORD dwMask,[in] UINT nDelay);
		[helpstring("method Init")] HRESULT Init([in] short begin, [in] short end, [in] short inc);
		[helpstring("method Increment")] HRESULT Increment();
		[helpstring("method UpdateMessage")] HRESULT UpdateMessage([in] LPCTSTR msg);
		[helpstring("method Continue")] HRESULT Continue();
		[helpstring("method DestroyProgressWindow")] HRESULT DestroyProgressWindow();
	};

   [
		uuid(BD40316D-259A-11D2-8EB0-006097DF3C68),
		helpstring("IAgent Interface"),
		pointer_default(unique)
	]
	interface IAgent : IUnknown
	{
		[helpstring("method SetBroker")] HRESULT SetBroker([in] IBroker* pBroker);
		[helpstring("method RegInterfaces")] HRESULT RegInterfaces();
		[helpstring("method Init")] HRESULT Init();
		[helpstring("method Reset")] HRESULT Reset();
		[helpstring("method ShutDown")] HRESULT ShutDown();
	};
	[
	   uuid(0AE540FE-8525-4db3-BC36-31B90E74830B),
	   helpstring("IAgentEx Interface"),
	   pointer_default(unique)
	]
	interface IAgentEx : IAgent
	{
		[helpstring("method Init2")] HRESULT Init2();
		[helpstring("method GetClassID")] HRESULT GetClassID([out]CLSID* pCLSID);
	};
	[
		uuid(E6268300-26FA-11d2-8EB0-006097DF3C68),
		helpstring("IAgentPersist Interface"),
		pointer_default(unique)
	]
	interface IAgentPersist : IUnknown
	{
		[helpstring("method Load")] HRESULT Load([in] IStructuredLoad* pStrLoad);
		[helpstring("method Save")] HRESULT Save([in] IStructuredSave* pStrSave);
	};

   [
      uuid(79B52B0A-B19B-4dc9-80B7-9EF36157A2B9),
      helpstring("IAgentUIIntegration"),
      pointer_default(unique)
   ]
   interface IAgentUIIntegration : IUnknown
   {
      [helpstring("method IntegrateWithUI")] HRESULT IntegrateWithUI(BOOL bIntegrate);
   }

   [
      uuid(B03A0005-11F8-40c3-8D18-D94032886129),
      helpstring("IAgentReportingIntegration"),
      pointer_default(unique)
   ]
   interface IAgentReportingIntegration : IUnknown
   {
      [helpstring("method IntegrateWithReporting")] HRESULT IntegrateWithReporting(BOOL bIntegrate);
   }

   [
      uuid(9AF52AB6-BECA-4aa4-8242-C7910B11AA08),
      helpstring("IAgentGraphingIntegration"),
      pointer_default(unique)
   ]
   interface IAgentGraphingIntegration : IUnknown
   {
      [helpstring("method IntegrateWithGraphing")] HRESULT IntegrateWithGraphing(BOOL bIntegrate);
   }

   [
      uuid(369EE64B-5135-4b0a-95F3-C3B001A39D6F),
      helpstring("IAgentDocumentationIntegration"),
      pointer_default(unique)
   ]
   interface IAgentDocumentationIntegration : IUnknown
   {
      [helpstring("method GetDocumentationSetName")] HRESULT GetDocumentationSetName(BSTR* pbstrName);
      [helpstring("method LoadDocumentationMap")] HRESULT LoadDocumentationMap();
      [helpstring("method GetDocumentLocation")] HRESULT GetDocumentLocation(UINT nHID,BSTR* pbstrURL);
   }

	[
		uuid(53CAB1E0-262E-11d2-8EB0-006097DF3C68),
		helpstring("IBrokerInit Interface"),
		pointer_default(unique)
	]
	interface IBrokerInit : IUnknown
	{
		[helpstring("method LoadAgents")] HRESULT LoadAgents([in] CLSID* pClsid, [in] IndexType nClsid,[out] IndexType* lErrIndex);
		[helpstring("method AddAgent")] HRESULT AddAgent([in] IAgent* pAgent);
		[helpstring("method FindConnectionPoint")] HRESULT FindConnectionPoint([in] REFIID riid,[out] IConnectionPoint** ppCP);
		[helpstring("method RegInterface")] HRESULT RegInterface([in] REFIID riid,[in] IAgent* pAgent);
	};

	[
		uuid(673DC477-468D-4466-98AA-53EE7A0EECA5),
		helpstring("IBrokerInitEx Interface"),
		pointer_default(unique)
	]
	interface IBrokerInitEx : IUnknown
	{
		[helpstring("method LoadAgents")] HRESULT LoadAgents([in] CLSID* pClsid, [in] IndexType nClsid,[out] IIndexArray** lErrIndex);
		[helpstring("method LoadExtensionAgents")] HRESULT LoadExtensionAgents([in] CLSID* pClsid, [in] IndexType nClsid,[out] IIndexArray** lErrIndex);
		[helpstring("method AddAgent")] HRESULT AddAgent([in] IAgentEx* pAgent);
		[helpstring("method AddExtensionAgent")] HRESULT AddExtensionAgent([in] IAgentEx* pAgent);
		[helpstring("method FindConnectionPoint")] HRESULT FindConnectionPoint([in] REFIID riid,[out] IConnectionPoint** ppCP);
		[helpstring("method RegInterface")] HRESULT RegInterface([in] REFIID riid,[in] IAgentEx* pAgent);
	};

	[
		uuid(7E70337A-DED7-43ae-936F-824EB1127012),
		helpstring("IBrokerInit2 Interface"),
		pointer_default(unique)
	]
	interface IBrokerInit2 : IBrokerInit
	{
		[helpstring("method DelayInit")] HRESULT DelayInit();
		[helpstring("method InitAgents")] HRESULT InitAgents();
	};

	[
		uuid(F4A9DD8F-273D-4ae6-B044-AC9DEAFD43D4),
		helpstring("IBrokerInitEx2 Interface"),
		pointer_default(unique)
	]
	interface IBrokerInitEx2 : IBrokerInitEx
	{
		[helpstring("method DelayInit")] HRESULT DelayInit();
		[helpstring("method InitAgents")] HRESULT InitAgents();
	};

	[
		uuid(94B63C86-A159-4330-80AA-D16618A7FFCB),
		helpstring("IBrokerInitEx3 Interface"),
		pointer_default(unique)
	]
	interface IBrokerInitEx3 : IBrokerInitEx2
	{
		[helpstring("method Integrate")] HRESULT Integrate(BOOL bIntegrateWithUI,BOOL bIntegrateWithReporting,BOOL bIntegrateWithGraphing,BOOL bIntegrateWithDocumentation);
		[helpstring("method RemoveIntegration")] HRESULT RemoveIntegration();
	};

   [
      uuid(1ED36EAA-D850-424c-96D6-3A993DB5EECF),
      helpstring("ICLSIDMap Interface"),
      pointer_default(unique)
   ]
   interface ICLSIDMap : IUnknown
   {
      [helpstring("method AddCLSID")] HRESULT AddCLSID(BSTR bstrOldCLSID,BSTR bstrNewCLSID);
   };

	[
		uuid(C0E926D0-2620-11D2-8EB0-006097DF3C68),
		helpstring("IBroker Interface"),
		pointer_default(unique)
	]
	interface IBroker : IUnknown
	{
		[helpstring("method GetInterface")] HRESULT GetInterface([in] REFIID riid, [out,iid_is(riid)] IUnknown** ppUnk);
		[helpstring("method Reset")] HRESULT Reset();
		[helpstring("method ShutDown")] HRESULT ShutDown();
	};
	[
		uuid(E6268301-26FA-11d2-8EB0-006097DF3C68),
		helpstring("IBrokerPersist Interface"),
		pointer_default(unique)
	]
	interface IBrokerPersist : IUnknown
	{
		[helpstring("method Load")] HRESULT Load([in] IStructuredLoad* pStrLoad);
		[helpstring("method Save")] HRESULT Save([in] IStructuredSave* pStrSave);
   };
	[
		uuid(2D663F88-1B17-4d1b-9DE8-8CD06050E2C2),
		helpstring("IBrokerPersist2 Interface"),
		pointer_default(unique)
	]
	interface IBrokerPersist2 : IBrokerPersist
	{
      [helpstring("method SetSaveMissingAgentDataFlag")] HRESULT SetSaveMissingAgentDataFlag([in]VARIANT_BOOL bSetFlag);
      [helpstring("method GetSaveMissingAgentDataFlag")] HRESULT GetSaveMissingAgentDataFlag([out]VARIANT_BOOL* bFlag);
   };

   [
      uuid(57EC999E-BCC8-4227-B415-AE9537668173),
      pointer_default(unique)
   ]
   interface IManageAgents : IUnknown
   {
      [propget] HRESULT AgentCount([out,retval]CollectionIndexType* nAgents);
      [propget] HRESULT Agent([in]CollectionIndexType idx,[out,retval]IAgent** ppAgent);
      [propget] HRESULT ExtensionAgentCount([out,retval]CollectionIndexType* nAgents);
      [propget] HRESULT ExtensionAgent([in]CollectionIndexType idx,[out,retval]IAgent** ppAgent);
   };

	[
		uuid(C0E926D1-2620-11D2-8EB0-006097DF3C68),
		helpstring("Broker Class")
	]
	coclass Broker
	{
		[default] interface IBroker;
		interface IBrokerInit;
		interface IBrokerPersist;
      interface IManageAgents;
	};
	[
		uuid(CF37B1E5-F9B8-4e78-B8B3-B91E326131CD),
		helpstring("Broker2 Class")
	]
	coclass Broker2
	{
		[default] interface IBroker;
		interface IBrokerInitEx3;
		interface IBrokerInitEx2;
		interface IBrokerPersist;
      interface ICLSIDMap;
	};
	[
	   uuid(D71212B0-2BEF-11d2-8EB3-006097DF3C68),
	   helpstring("SysAgent Class")
	]
	coclass SysAgent
	{
	   [default] interface IAgent;
	   interface IProgress;
	   interface ILogFile;
	};
};
