//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DManip.rc
//
#define IDC_TARGET                      2001
#define IDC_MAGNIFY                     2002

#define IDR_DISPLAYLIST                 2010
#define IDR_DISPLAYMGR                  2011
#define IDR_INPLACEEDITTASK             2012
#define IDR_RECTSELECTTASK              2013
#define IDR_LOCALDRAGDROPTASK           2014
#define IDR_FOREIGNDRAGDROPTASK         2015
#define IDR_DRAGDATASOURCE              2016
#define IDR_DRAGDATASINK                2017
#define IDR_CENTERONPOINTTASK           2018
#define IDR_ZOOMRECTTASK                2019
#define IDR_TASKFACTORY                 2020
#define IDR_DISPLAYOBJECTFACTORY        2021
#define IDR_MAPPING			2022
#define IDR_PLUG			2023
#define IDR_SOCKET			2024
#define IDR_SOCKETFACTORY               2025
#define IDR_POINTDISPLAYOBJECT		2026
#define IDR_SIMPLEDRAWPOINTSTRATEGY	2027
#define IDR_TEXTBLOCK			2028
#define IDR_EDITABLETEXTBLOCK		2029
#define IDR_EDITABLEUNITVALUETEXTBLOCK	2030
#define IDR_LINEDISPLAYOBJECT		2031
#define IDR_DIMENSIONLINEDISPLAYOBJECT	2032
#define IDR_TOOL			2033
#define IDR_COMPOSITEDISPLAYOBJECT	2034
#define IDR_SIMPLEDRAWLINESTRATEGY	2035
#define IDR_SIMPLEDRAWDASHEDLINESTRATEGY	2036
#define IDR_RECTANGLEDRAWLINESTRATEGY	2037
#define IDR_SHAPEDRAWSTRATEGY		2038
#define IDR_TARGETDRAWSTRATEGY		2039
#define IDR_COMPOUNDDRAWLINESTRATEGY	2040
#define IDR_COMPOUNDDRAWPOINTSTRATEGY 2041
#define IDR_EXTRECTANGLEDRAWLINESTRATEGY	2042
#define IDR_VIEWTITLE			2043
#define IDR_NORTHARROW			2044
#define IDR_SHAPEGRAVITYWELLSTRATEGY	2045
#define IDR_ANCHOREDTEXTBLOCK 2046

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        2007
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         2000
#define _APS_NEXT_SYMED_VALUE           2001
#endif
#endif
