//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by EAF.rc
//
#define IDOK2                           3
#define IDEDIT                          3
#define IDS_UPDATE_IN_PROGRESS          102
#define IDB_LIGHTBULB                   103
#define IDD_TIP                         104
#define CG_IDS_TIPOFTHEDAYMENU          106
#define CG_IDS_DIDYOUKNOW               107
#define CG_IDS_FILE_ABSENT              108
#define CG_IDP_FILE_CORRUPT             109
#define CG_IDS_TIPOFTHEDAYHELP          110
#define IDR_MAINFRAME                   128
#define IDD_NEWPROJECT                  132
#define IDD_UNITS                       133
#define IDD_MANAGE_PLUGINS              135
#define IDR_RECENT_FILE                 136
#define IDD_EDIT_CUSTOM_REPORT          139
#define IDD_CUSTOM_REPORTS_PAGE         140
#define IDD_EXPORT_CUSTOM_REPORTS       141
#define IDD_CUSTOM_REPORT_CONFLICT      142
#define IDD_RENAME_REPORT_DLG           143
#define IDB_CREPORT_BMP                 145
#define IDD_STATUS_DIALOG               146
#define IDR_HELP                        147
#define IDI_LARGEICON                   150
#define IDI_SMALLICON                   151
#define IDI_HELP                        152
#define IDD_DIALOG1                     152
#define IDD_AUTOSAVE                    152
#define IDB_LPFRAME                     154
#define IDD_TOOLBARS                    159
#define IDC_EDIT                        200
#define IDD_ABOUTBOX                    999
#define IDC_VERSION                     1002
#define IDC_COPYRIGHT                   1003
#define IDC_STARTUP                     1003
#define IDC_APPICON                     1005
#define IDC_NEXTTIP                     1005
#define IDD_STATUSCENTER                1006
#define IDC_STATUSLIST                  1007
#define IDC_PROJECTTYPES                1007
#define IDC_LABEL                       1008
#define IDC_LIST1                       1008
#define IDC_TEMPLATES                   1008
#define IDC_TIPSTRING                   1008
#define IDC_FAVORITE_LIST               1008
#define IDC_AVAILABLE_LIST              1008
#define IDC_US_UNITS                    1009
#define IDC_DESCRIPTION                 1009
#define IDC_SELECTED_LIST               1009
#define IDC_SI_UNITS                    1010
#define IDC_LARGE                       1010
#define IDC_SMALL                       1011
#define IDC_MOREINFO                    1013
#define IDC_CHECK1                      1015
#define IDC_CUSTOM_REPORT_LIST          1017
#define IDC_ADDNEW                      1018
#define IDC_DELETE                      1020
#define IDC_REPORT_NAME                 1021
#define IDC_PARENT_COMBO                1022
#define IDC_ADD_BUTTON                  1023
#define IDC_REMOVE_BUTTON               1024
#define IDC_LIST                        1025
#define IDC_MOVE_UP_BUTTON              1025
#define IDC_MOVE_DOWN_BUTTON            1026
#define IDC_EXPORT                      1026
#define IDC_IMPORT                      1027
#define IDC_ADD_ALL_BUTTON              1027
#define ID_SKIP                         1028
#define IDC_REMOVE_ALL_BUTTON           1028
#define ID_RENAME                       1029
#define IDC_REPORT_NAME_STATIC          1030
#define IDC_NAME_STATIC                 1031
#define IDC_EDIT1                       1032
#define IDC_REPORT_NAME_EDIT            1032
#define IDC_INTERVAL                    1032
#define IDC_INFORMATION                 1034
#define IDC_WARNING                     1035
#define IDC_ERROR                       1036
#define IDREMOVE                        1037
#define IDC_ENABLE                      1038
#define IDC_INTERVAL_LABEL              1039
#define IDC_PLUGIN_LIST                 1108
#define IDD_UIHINTS                     1135
#define IDC_TOOLTIPS                    1156
#define IDC_TEXT                        1225
#define IDC_DONTSHOWAGAIN               1226
#define IDS_E_NOBROWSER                 1648
#define IDS_E_UPDATE                    1649
#define IDS_RESULTS_NOT_AVAILABLE       1697
#define IDS_FATAL_MSG_SAVE              1713
#define IDS_FATAL_MSG_NOSAVE            1715
#define IDS_TOOLBAR_STATE               1730
#define IDS_REG_SETTINGS                1733
#define IDS_TOOLTIP_STATE               1735
#define IDS_WINDOW_POSITIONS            1737
#define IDS_WORKING                     1746
#define IDC_APPLIST                     3333
#define IDC_REPORT_WEB_BROWSER          5001
#define IDC_INTERVAL_UNITS              5001
#define IDD_SELECTREPORT                12925
#define IDD_FAVORITE_REPORT_DLG         12926
#define IDC_FRAME                       13012
#define IDC_MESSAGE                     13013
#define IDC_GROUP                       13014
#define IDC_MY_ICON                     13015
#define IDS_E_CREATEWND                 61446
#define IDS_E_LOWRESOURCES              61447
#define IDS_E_FORMAT                    61448
#define IDS_E_BADINSTALL                61449
#define IDS_E_PROBPERSISTS              61450
#define IDS_E_UNSAFESAVE                61451

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        154
#define _APS_NEXT_COMMAND_VALUE         32778
#define _APS_NEXT_CONTROL_VALUE         1040
#define _APS_NEXT_SYMED_VALUE           1015
#endif
#endif
